// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rc.proto

/*
Package rc is a generated protocol buffer package.

It is generated from these files:
	rc.proto

It has these top-level messages:
	Empty
	State
*/
package rc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type State struct {
	TsCurrent int32  `protobuf:"varint,1,opt,name=ts_current,json=tsCurrent" json:"ts_current,omitempty"`
	TsTotal   int32  `protobuf:"varint,2,opt,name=ts_total,json=tsTotal" json:"ts_total,omitempty"`
	State     int32  `protobuf:"varint,3,opt,name=state" json:"state,omitempty"`
	Source    string `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
	Dest      string `protobuf:"bytes,5,opt,name=dest" json:"dest,omitempty"`
}

func (m *State) Reset()                    { *m = State{} }
func (m *State) String() string            { return proto.CompactTextString(m) }
func (*State) ProtoMessage()               {}
func (*State) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *State) GetTsCurrent() int32 {
	if m != nil {
		return m.TsCurrent
	}
	return 0
}

func (m *State) GetTsTotal() int32 {
	if m != nil {
		return m.TsTotal
	}
	return 0
}

func (m *State) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *State) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *State) GetDest() string {
	if m != nil {
		return m.Dest
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "rc.Empty")
	proto.RegisterType((*State)(nil), "rc.State")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PrivateTV service

type PrivateTVClient interface {
	GetState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*State, error)
}

type privateTVClient struct {
	cc *grpc.ClientConn
}

func NewPrivateTVClient(cc *grpc.ClientConn) PrivateTVClient {
	return &privateTVClient{cc}
}

func (c *privateTVClient) GetState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*State, error) {
	out := new(State)
	err := grpc.Invoke(ctx, "/rc.PrivateTV/GetState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PrivateTV service

type PrivateTVServer interface {
	GetState(context.Context, *Empty) (*State, error)
}

func RegisterPrivateTVServer(s *grpc.Server, srv PrivateTVServer) {
	s.RegisterService(&_PrivateTV_serviceDesc, srv)
}

func _PrivateTV_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateTVServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rc.PrivateTV/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateTVServer).GetState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrivateTV_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rc.PrivateTV",
	HandlerType: (*PrivateTVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _PrivateTV_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rc.proto",
}

func init() { proto.RegisterFile("rc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8f, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0x2b, 0xd7, 0xb2, 0xad, 0x1b, 0x8f, 0x52, 0xd4, 0x42, 0xc1, 0x68, 0xf2, 0xe4, 0x42,
	0xfb, 0x13, 0x4a, 0xe9, 0x5a, 0x1c, 0x93, 0xd5, 0x38, 0x8a, 0x86, 0x40, 0x12, 0x99, 0xd3, 0x39,
	0x90, 0x39, 0x7f, 0x3c, 0xf8, 0x9c, 0xed, 0x7d, 0xdf, 0xc1, 0xf1, 0x1e, 0x54, 0xe4, 0xdb, 0x89,
	0x22, 0x47, 0xcc, 0xc8, 0xbb, 0x12, 0xf4, 0xef, 0x69, 0xe2, 0xab, 0xbb, 0x29, 0xd0, 0x1b, 0x1e,
	0x39, 0xe0, 0x07, 0x00, 0xa7, 0xc1, 0xcf, 0x44, 0xe1, 0xcc, 0x56, 0xd5, 0xaa, 0xd1, 0x9d, 0xe1,
	0xf4, 0xb3, 0x0a, 0x7c, 0x83, 0x8a, 0xd3, 0xc0, 0x91, 0xc7, 0xa3, 0xcd, 0xe4, 0x58, 0x72, 0xea,
	0x17, 0xc4, 0x17, 0xd0, 0x69, 0x79, 0x61, 0x9f, 0xc5, 0xaf, 0x80, 0xaf, 0x50, 0xa4, 0x38, 0x93,
	0x0f, 0x36, 0xaf, 0x55, 0x63, 0xba, 0x07, 0x21, 0x42, 0xbe, 0x0f, 0x89, 0xad, 0x16, 0x2b, 0xf9,
	0xeb, 0x13, 0xcc, 0x3f, 0x1d, 0x2e, 0x23, 0x87, 0x7e, 0x8b, 0x0e, 0xaa, 0xbf, 0xc0, 0x6b, 0x29,
	0xd3, 0x92, 0x6f, 0xa5, 0xe9, 0xbb, 0x44, 0xb1, 0xee, 0x69, 0x57, 0xc8, 0x94, 0xef, 0x7b, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf7, 0x28, 0x8c, 0x51, 0xd6, 0x00, 0x00, 0x00,
}
